import { useServerFn } from "@tanstack/react-start";
import { ArrowLeft, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  ErrorNote,
  FeedbackList,
  NextButton,
  Notice,
  SectionLabel,
  StepView,
} from "@/components/common";
import { ProfessionalCard } from "@/components/ProfessionalCard";
import { reviewQuestion } from "@/api/coach.functions";
import type { Professional } from "@/config/professionals";
import { checkQuestion } from "@/domain/questionCheck";
import { useAsyncAction } from "@/hooks/useAsyncAction";
import { useLiveAi } from "@/hooks/useIntegrationStatus";
import { useJourney } from "@/journey/JourneyProvider";
import { hasPreparedQuestions, professionalFor, type PreparedQuestion } from "@/journey/state";

export function PrepareStep() {
  const { state, update, goTo } = useJourney();
  const professional = professionalFor(state);
  const live = useLiveAi(state.sampleMode);

  const setQuestion = (index: 0 | 1, question: PreparedQuestion) => {
    const next = [...state.preparedQuestions] as typeof state.preparedQuestions;
    next[index] = question;
    update({ preparedQuestions: next });
  };

  return (
    <StepView
      label="03 / Prepare"
      title={`Meet ${professional.name}.`}
      lead="Read their profile, then write two questions you'd like to ask. You'll talk with them out loud next."
    >
      <ProfessionalCard professional={professional} />
      <div className="single-panel fade-up mt-8">
        <SectionLabel>Your questions</SectionLabel>
        <h2>Prepare two questions worth answering.</h2>
        <p className="lesson-copy">
          Use what you learned: open-ended, about their own experience, one question at a time.
        </p>
        {([0, 1] as const).map((index) => (
          <QuestionEditor
            key={`${professional.id}-${index}`}
            index={index}
            question={state.preparedQuestions[index]}
            professional={professional}
            live={live}
            onChange={(q) => setQuestion(index, q)}
          />
        ))}
        <div className="panel-actions">
          <Button variant="ghost" onClick={() => goTo("lesson")}>
            <ArrowLeft size={16} /> Back to lesson
          </Button>
          <NextButton onClick={() => goTo("roleplay")} disabled={!hasPreparedQuestions(state)}>
            I'm ready for the conversation
          </NextButton>
        </div>
        <Notice>
          {live
            ? "Feedback is generated by AI."
            : "Sample feedback uses editable rules, not live AI."}{" "}
          {professional.name} is fictional.
        </Notice>
      </div>
    </StepView>
  );
}

function QuestionEditor({
  index,
  question,
  professional,
  live,
  onChange,
}: {
  index: 0 | 1;
  question: PreparedQuestion;
  professional: Professional;
  live: boolean;
  onChange: (question: PreparedQuestion) => void;
}) {
  const { pending, error, run } = useAsyncAction();
  const review = useServerFn(reviewQuestion);
  const id = `prepared-question-${index}`;

  const getFeedback = () =>
    run(async () => {
      const text = question.text.trim();
      const feedback = live
        ? await review({ data: { question: text, professionalId: professional.id } })
        : checkQuestion(text, professional.role);
      onChange({ text, feedback });
    });

  const { feedback } = question;
  const canRevise = feedback && feedback.revision.trim() !== question.text.trim();

  return (
    <div className="question-block">
      <label className="field-label" htmlFor={id}>
        Question {index + 1}
      </label>
      <textarea
        id={id}
        className="field-input question-input"
        rows={2}
        placeholder={
          index === 0
            ? "What would you like to know about their work?"
            : "What would you like to know about their path?"
        }
        value={question.text}
        onChange={(e) => onChange({ text: e.target.value, feedback: null })}
      />
      <div className="question-actions">
        <Button
          variant="outline"
          size="sm"
          onClick={getFeedback}
          disabled={!question.text.trim() || pending}
        >
          {pending ? "Reading your question…" : "Get feedback"}
        </Button>
      </div>
      <ErrorNote message={error} />
      {feedback && (
        <>
          <FeedbackList
            items={[
              { label: "What works", text: feedback.works },
              { label: "One improvement", text: feedback.improve },
              { label: "A possible revision", text: `“${feedback.revision}”` },
            ]}
          />
          {canRevise && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => onChange({ text: feedback.revision, feedback: null })}
            >
              <RotateCcw size={14} /> Use this revision
            </Button>
          )}
        </>
      )}
    </div>
  );
}
