import { useEffect, useRef } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Compass, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChatPanel } from "@/components/ChatPanel";
import { ErrorNote, FeedbackList, Notice, SectionLabel, StepView } from "@/components/common";
import { askReflectionCoach, reviewConversation } from "@/api/coach.functions";
import { sampleCoachReply } from "@/config/content";
import { formatClock } from "@/config/roleplay";
import { buildSampleFeedback } from "@/domain/conversationFeedback";
import type { ChatMessage, ConversationFeedback } from "@/domain/types";
import { useAsyncAction } from "@/hooks/useAsyncAction";
import { useLiveAi } from "@/hooks/useIntegrationStatus";
import { useJourney } from "@/journey/JourneyProvider";
import { professionalFor, resetRolePlay } from "@/journey/state";

const feedbackItems = (f: ConversationFeedback) => [
  { label: "One thing you did well", text: f.strength },
  { label: "One thing to practice", text: f.practice },
  { label: "A moment from your conversation", text: `“${f.quote}”`, note: f.quoteComment },
  { label: "Your prepared questions", text: f.preparedQuestionsUsed },
  { label: "Something you learned about the career", text: f.careerInsight },
];

const summarize = (f: ConversationFeedback) =>
  feedbackItems(f)
    .map((i) => `${i.label}: ${i.text}`)
    .join("\n");

export function ReflectStep() {
  const { state, update, goTo } = useJourney();
  const professional = professionalFor(state);
  const live = useLiveAi(state.sampleMode);
  const feedbackTask = useAsyncAction();
  const chatTask = useAsyncAction();
  const review = useServerFn(reviewConversation);
  const ask = useServerFn(askReflectionCoach);
  const requested = useRef(false);
  const preparedQuestions = state.preparedQuestions.map((q) => q.text);

  const generateFeedback = () =>
    feedbackTask.run(async () => {
      const feedback =
        live && state.profile
          ? await review({
              data: {
                transcript: state.transcript,
                preparedQuestions,
                professionalId: professional.id,
                profile: state.profile,
              },
            })
          : buildSampleFeedback(state.transcript, preparedQuestions);
      update({ feedback });
    });

  useEffect(() => {
    if (state.feedback || requested.current) return;
    requested.current = true;
    void generateFeedback();
  }, [state.feedback]); // eslint-disable-line react-hooks/exhaustive-deps

  const sendToCoach = (text: string) =>
    chatTask.run(async () => {
      const history: ChatMessage[] = [...state.reflectionChat, { role: "student", text }];
      update({ reflectionChat: history });
      const reply =
        live && state.feedback
          ? (
              await ask({
                data: {
                  history,
                  transcript: state.transcript,
                  professionalId: professional.id,
                  feedbackSummary: summarize(state.feedback),
                },
              })
            ).text
          : sampleCoachReply;
      update({ reflectionChat: [...history, { role: "coach", text: reply, sample: !live }] });
    });

  const practiceAgain = () => {
    update(resetRolePlay());
    goTo("roleplay");
  };

  return (
    <StepView
      label="05 / Reflect"
      title="Nice work — let's look back together."
      lead={`You talked with ${professional.name} for ${formatClock(state.rolePlaySeconds)}. Here's what stood out, based on what you actually said.`}
    >
      <div className="single-panel fade-up">
        <SectionLabel>Coach feedback</SectionLabel>
        <h2>What Sariel noticed</h2>
        {state.feedback ? (
          <FeedbackList items={feedbackItems(state.feedback)} />
        ) : (
          <p className="quiet mt-4">{feedbackTask.pending ? "Reading your conversation…" : ""}</p>
        )}
        <ErrorNote message={feedbackTask.error} />
        {feedbackTask.error && (
          <Button variant="outline" className="mt-4" onClick={generateFeedback}>
            Try again
          </Button>
        )}
        <Notice>
          {live
            ? "Feedback is generated by AI from your transcript."
            : "Sample feedback uses simple rules applied to your transcript."}
        </Notice>
      </div>

      <div className="mt-8">
        <ChatPanel
          title="Ask Sariel"
          caption="Coach mode"
          messages={
            state.reflectionChat.length
              ? state.reflectionChat
              : [
                  {
                    role: "coach",
                    text: "Any questions about how it went, or what to try next time?",
                  },
                ]
          }
          onSend={sendToCoach}
          waiting={chatTask.pending}
          disabled={!state.feedback}
          placeholder="e.g. How could I have followed up better?"
        />
        <ErrorNote message={chatTask.error} />
      </div>

      <div className="panel-actions">
        <Button variant="outline" onClick={practiceAgain}>
          <RotateCcw size={16} /> Practice again
        </Button>
        <Button onClick={() => goTo("onboarding")}>
          <Compass size={16} /> Explore another career area
        </Button>
      </div>
    </StepView>
  );
}
